# Generated by Django 2.2.13 on 2020-06-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bild',
            field=models.ImageField(default='Bild', upload_to=''),
            preserve_default=False,
        ),
    ]
