# Generated by Django 2.2.13 on 2020-07-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200710_1055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kontakt',
            new_name='Message',
        ),
    ]
