# Generated by Django 2.2.13 on 2020-07-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200706_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('nachricht', models.TextField()),
                ('created_on_day', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_on_day'],
            },
        ),
    ]
