# Generated by Django 2.2.13 on 2020-06-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_text2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text2',
        ),
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.CharField(default='place', max_length=100),
            preserve_default=False,
        ),
    ]
