# Generated by Django 2.2.13 on 2020-06-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_bild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bild',
            field=models.ImageField(blank=True, upload_to='post_list'),
        ),
    ]
