# Generated by Django 2.2.12 on 2020-06-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200615_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.CharField(default='place', max_length=100),
            preserve_default=False,
        ),
    ]
