# Generated by Django 2.2.13 on 2020-06-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200615_1159'),
        ('blog', '0003_auto_20200615_1316'),
    ]

    operations = [
    ]
