# Generated by Django 2.2.13 on 2020-06-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_merge_20200615_1342'),
        ('blog', '0004_post_place'),
    ]

    operations = [
    ]
