# Generated by Django 2.2.13 on 2020-06-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_merge_20200615_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.CharField(default='age', max_length=10),
            preserve_default=False,
        ),
    ]
