# Generated by Django 2.2.13 on 2020-06-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titel',
        ),
    ]
