# Generated by Django 2.2.13 on 2020-06-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200615_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='age',
            new_name='alter',
        ),
    ]
