# Generated by Django 2.2.13 on 2020-06-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200615_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='age',
            new_name='alter',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='place',
            new_name='ort',
        ),
        migrations.AlterField(
            model_name='post',
            name='bild',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='images/'),
        ),
    ]
