# Generated by Django 2.2.13 on 2020-06-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200617_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='place',
            new_name='ort',
        ),
    ]
