# Generated by Django 2.2.13 on 2020-06-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200624_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='place',
        ),
    ]
