# Generated by Django 2.2.12 on 2020-06-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200617_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='place',
        ),
    ]
