# Generated by Django 2.2.12 on 2020-06-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bild',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
