# Generated by Django 2.2.12 on 2020-06-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200620_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bild',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='media'),
        ),
    ]
