# Generated by Django 2.2.13 on 2020-06-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200620_1147'),
        ('blog', '0009_remove_post_place'),
    ]

    operations = [
    ]
